name: Update Monkeytype PBs

on:
  schedule:
    - cron: "17 2 * * *"  # daily at 02:17 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      MONKEYTYPE_USERNAME: wambo
      MONKEYTYPE_API_KEY: ${{ secrets.MONKEYTYPE_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update README with Monkeytype PBs
        run: node scripts/update-monkeytype.js

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update Monkeytype personal bests"
            git push
          fi
